### ISSUE TITLE
.github/FUNDING.yml

### ISSUE THREAD

**Issue by azu** [asciidwango/js-primer#1146]
@lacolaco `.github/FUNDING.yml` を追加しようと思いますが、どうですか?

```yaml
github: azu
patreon: lacolaco
custom: ["https://www.amazon.co.jp/dp/4048930737/"]
```

![image](https://user-images.githubusercontent.com/19714/78904995-4f3a1880-7ab8-11ea-9197-f2182b900e6d.png)

GitHub以外はアイコンとかでなくて情報が不公平なので、なしでもいいかなーと試してみて思った部分もある。
