### ISSUE TITLE
注釈を挿入する場合に矢印などが欲しいです

### ISSUE THREAD

**Issue by sin1rou** [asciidwango/js-primer#787]
## 該当ページ

source/basic/class/README.md
source/basic/function-declaration/README.md
source/basic/function-scope/README.md
source/basic/function-this/README.md
source/basic/string/README.md
(一部)

## リクエスト/提案内容

注釈を挿入する際に、数字で統一するか矢印を付けるかなどして注釈であることを明示した方がより読みやすくなるのではないかと思います。
ご検討よろしくお願いします。

**Comment by azu** [comment]
ありがとうございます。

https://jsprimer.net/basic/class/#fn_%E7%B3%96%E8%A1%A3%E6%A7%8B%E6%96%87
![image](https://user-images.githubusercontent.com/19714/58378734-bac7e400-7fd3-11e9-81ab-68aaf7d7d3e7.png)

みたいな脚注のことですかね?
GitBookの脚注記法をそのまま表示してるだけなので、なにかできないか考えてみます。

CSSの[counter-increment](https://developer.mozilla.org/ja/docs/Web/CSS/counter-increment)とかで連番を振っていくとかかな。

```css
sup {
    counter-increment: footmark;
}

sup::before {
    content: counter(footmark);
}
```
